### ISSUE TITLE
Understanding

### ISSUE THREAD

**Issue by unixb0y** [gwenvador/dca_kraken#1]
Hello,
Thanks for putting this up here, it helped me implement something similar in Python for another currency pair.
I'm not understanding how this is supposed to be DCA though: Your script puts all buy orders in at once right? I mean, in a loop yes, but it's not waiting. I would've expected it to e.g. put in an order, then wait a day then do the next etc.
I'd like to know what your strategy / idea is here or if I'm just misunderstanding your code :D
Cheers, Dave

**Comment by oktomus** [comment]
> I would've expected it to e.g. put in an order, then wait a day then do the next etc.
I'd like to know what your strategy / idea is here or if I'm just misunderstanding your code :D

In the README it is mentioned to use `crontab`, which will run the script on a daily / monthly / weekly / whatever basis.

**Comment by unixb0y** [comment]
Oh right okay. But what's the strategy with the many trades?

**Comment by oktomus** [comment]
Maybe you want to do different operations on a regular basis. Like buy some of this, and some of this

**Comment by oktomus** [comment]
Sorry I didn't understood the question clearly. The README mention the following : 

> In addition the script will put a certain number of buy trades (according to the quantity and remaining fiat reserve) at lower price to capture any fat finger trades.
The trade's distribution follow a function (10^x-1)/9 (https://www.desmos.com/calculator/tqckgq4ymf) which distributes trades to have the best possible gains.

So I guess this repo is not only about DCA.

**Comment by oktomus** [comment]
>  I'd like to know what your strategy / idea is here or if I'm just misunderstanding your code :D

So I took a closer look at the code and tried it myself. The strategy is simple : buy more if the token is cheaper.
To do so, many orders are created with the `limit` option. If the token price is under a certain amount, buy that amount. And of course, the amount is higher on orders with a lower limit price.

**Comment by unixb0y** [comment]
Ahh I see, interesting! Thanks for clarification, had no time to check (and not enough confidence to just try) it :D
